language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r svn/resources/requirements.txt
  - pip install coveralls
script: nosetests -s -v --with-coverage --cover-package=svn
after_success:
  - coveralls